package ru.learnup.javaqa.db.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Categories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sun Dec 26 18:17:40 MSK 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.title
     *
     * @mbg.generated Sun Dec 26 18:17:40 MSK 2021
     */
    private String title;

}